name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: app-helm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout
      
      - name: Log Checkout Status
        run: echo "Checkout completed with status: ${{ steps.checkout.outcome }}"

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        id: docker_login
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
      
      - name: Log Docker Login Status
        run: echo "Docker login completed with status: ${{ steps.docker_login.outcome }}"

      # Build Docker image
      - name: Build Docker image
        id: build_image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
      
      - name: Log Build Image Status
        run: echo "Docker build completed with status: ${{ steps.build_image.outcome }}"

      # Push Docker image to Docker Hub
      - name: Push Docker image
        id: push_image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Log Push Image Status
        run: echo "Docker push completed with status: ${{ steps.push_image.outcome }}"

      # Update values.yaml with the new APP_VERSION (using the GitHub commit SHA)
      - name: Update values.yaml
        id: update_yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml with latest version" || echo "No changes to commit"
          git push || echo "Push failed, likely no changes to push"
      
      - name: Log YAML Update Status
        run: echo "values.yaml update completed with status: ${{ steps.update_yaml.outcome }}"
